export default {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'editor-placeholder',
  paragraph: 'editor-paragraph',
  quote: 'editor-quote',
  heading: {
    h1: 'editor-heading-h1',
    h2: 'editor-heading-h2',
    h3: 'editor-heading-h3',
    h4: 'editor-heading-h4',
    h5: 'editor-heading-h5',
  },
  list: {
    listitem: 'editor-listitem',
    nested: {
      listitem: 'editor-nested-listitem',
    },
    ol: 'editor-list-ol',
    ul: 'editor-list-ul',
  },
  image: 'editor-image',
  link: 'editor-link',
  embedBlock: {
    base: 'editor-embedBlock',
    focus: 'editor-embedBlockFocus',
  },
  text: {
    bold: 'editor-text-bold',
    code: 'editor-text-code',
    hashtag: 'editor-text-hashtag',
    italic: 'editor-text-italic',
    overflowed: 'editor-text-overflowed',
    strikethrough: 'editor-text-strikethrough',
    underline: 'editor-text-underline',
    underlineStrikethrough: 'editor-text-underlineStrikethrough',
  },
  code: 'editor-code',
  codeHighlight: {
    atrule: "editor-tokenAttr",
    attr: "editor-tokenAttr",
    boolean: "editor-tokenProperty",
    builtin: "editor-tokenSelector",
    cdata: "editor-tokenComment",
    char: "editor-tokenSelector",
    class: "editor-tokenFunction",
    "class-name": "editor-tokenFunction",
    comment: "editor-tokenComment",
    constant: "editor-tokenProperty",
    deleted: "editor-tokenProperty",
    doctype: "editor-tokenComment",
    entity: "editor-tokenOperator",
    function: "editor-tokenFunction",
    important: "editor-tokenVariable",
    inserted: "editor-tokenSelector",
    keyword: "editor-tokenAttr",
    namespace: "editor-tokenVariable",
    number: "editor-tokenProperty",
    operator: "editor-tokenOperator",
    prolog: "editor-tokenComment",
    property: "editor-tokenProperty",
    punctuation: "editor-tokenPunctuation",
    regex: "editor-tokenVariable",
    selector: "editor-tokenSelector",
    string: "editor-tokenSelector",
    symbol: "editor-tokenProperty",
    tag: "editor-tokenProperty",
    url: "editor-tokenOperator",
    variable: "editor-tokenVariable"
  },
  table: 'editor-table',
  tableAddColumns: 'editor-table-addColumns',
  tableAddRows: 'editor-table-addRows',
  tableAlignment: {
    center: 'editor-table-alignmentCenter',
    right: 'editor-table-alignmentRight',
  },
  tableCell: 'editor-table-cell',
  tableCellActionButton: 'editor-table-cellActionButton',
  tableCellActionButtonContainer: 'editor-table-cellActionButtonContainer',
  tableCellHeader: 'editor-table-cellHeader',
  tableCellResizer: 'editor-table-cellResizer',
  tableCellSelected: 'editor-table-cellSelected',
  tableFrozenColumn: 'editor-table-frozenColumn',
  tableFrozenRow: 'editor-table-frozenRow',
  tableRowStriping: 'editor-table-rowStriping',
  tableScrollableWrapper: 'editor-table-scrollableWrapper',
  tableSelected: 'editor-table-selected',
  tableSelection: 'editor-table-selection',
};
